### ISSUE TITLE
Allow greater than 1,024 characters in chat interaction

### ISSUE THREAD

**Issue by WPrintz** [chat-cli/chat-cli#51]
When in chat mode, the io buffer limits the input to 1,024 characters, after which it stops allowing further entry in the chat prompt.  If possible, please take a look at the bufio to determine if an override is possible to allow (effectively) unlimited input into the terminal chat.  Thanks!

The issue occurs on MacOS Sonoma 14.7.1

**Comment by micahwalter** [comment]
Fixed in #52

**Comment by WPrintz** [comment]
@micahwalter Thanks for updating.  I updated to lastest v0.3.5 and still see limitation of 1024 characters when copy/pasting into an existing chat dialog.

**Comment by micahwalter** [comment]
ok interesting.. I will re-open. However, I am currently looking into re-writing the chat command entirely using a different interface, which will be much nicer and let you attach docs, save output, etc.

**Comment by micahwalter** [comment]
ok I believe the limit has to do with macOS limits for TTY input over stdin .. 

https://unix.stackexchange.com/questions/204815/terminal-does-not-accept-pasted-or-typed-lines-of-more-than-1024-characters

So really the right thing to do here is to allow for attachments / read from file as input.

**Comment by micahwalter** [comment]
This should be fixed in #75 and available in next release coming soon.
